### PR TITLE
Adding ConvertKit support to Rapidology

### PR DESCRIPTION
**Pull request by growdev**
Hi, I've added an integration with [ConvertKit's](http://convertkit.com/) API version [v3.0](http://kb.convertkit.com/article/api-documentation-v3/).

Please let me know if you have any questions or need an account to test with. 

Thanks!

### CODE REVIEW

**Comment by JBMeierLP** [comment]
@growdev  - this is fantastic!   I'll talk to the team about having this merged and included in a release.  Thank you - we really appreciate your efforts to improve this project.

**Comment by Rapidology** [comment]
Hey @growdev 
I did some initial testing and most of the integration looks good.
However a couple things that will need to be resolved / changed.
* If you visit the Email Accounts page after you add a Convert Kit integration you will see there is not logo for Convert Kit displayed http://screencast.com/t/DS5RFNCgGkTZ  This can be done by adding the image to the images folder in svg format. You can look at the MailChimp image for an example. Then add that image to the css in rapidology/css/admin.css starting around line 97

* I see you took out some lines for the autoupdate. We have resolved the issue with the timeout message showing up, if you could remove that fix on your end from the pull request we would appreciate it.

Once these are resolved, I will send this through our QA Dept. to test it. 
Thank you

**Comment by growdev** [comment]
@Rapidology Thanks for the feedback. I've re-added the updater and added a logo for ConvertKit.

**Comment by Rapidology** [comment]
@growdev Your integration has been merged into our QA workflow and I have added you to our authors.txt to give credit to your contribution to the plugin. Please let me me know if you would like it worded differently.

Daniel Espinoza - https://github.com/growdev
* Contributed ConvertKit integration to Rapidology

When its approved we will push our master branch to Github so this pull request won't actually be merged. Thank you again for your contribution.

**Comment by growdev** [comment]
Thanks guys! Excited to see it in the latest version! 

I'll close this PR.

**Pull request closed without merging**
